### ISSUE TITLE
How to calculate the position of the zero parallax plane？

### ISSUE THREAD

**Issue by smallPotatoBoy** [Vital-Volkov/Stereoscopic-3D-system-for-Unreal-Engine-5#4]
Dear Vitaly Volkov：
Could we see the location of the zero parallax plane in real time? 
And How to calculate the position of the zero parallax plane？
I am very confused,No progress has been made during this time.

anyway thanks for you help,
We are happy to communicate with you.

**Comment by Vital-Volkov** [comment]
Hi [smallPotatoBoy](https://github.com/smallPotatoBoy),

According to [this](https://www.researchgate.net/figure/Positive-zero-and-negative-parallax-top-view_fig3_278033341) "zero parallax plane" is "Screen Distance" in my system
 so after you set correct Pixels Per Inch of screen and User IPD 
just adjust Field Of View until Screen Distance matches your real distance from eyes to screen for a 100% realistic view.

Best regards.
